/**
 * 编辑页面或新建页面
 */
export const WYA_MODULES_INIT = 'WYA_MODULES_INIT';
export const WYA_MODULES_ADD = 'WYA_MODULES_ADD';
export const WYA_MODULES_UPDATE = 'WYA_MODULES_UPDATE';
export const WYA_MODULES_SORT = 'WYA_MODULES_SORT';
export const WYA_MODULES_DEL = 'WYA_MODULES_DEL';
export const WYA_MODULES_RESET = 'WYA_MODULES_RESET';
